{
  "magdaVersion": "0.0.0",
  "kind": "device",
  "payload": {
    "id": -1,
    "name": "Multiband Compressor",
    "pluginId": "magda_multiband",
    "manufacturer": "MAGDA",
    "format": 3,
    "isInstrument": false,
    "deviceType": 1,
    "uniqueId": "",
    "fileOrIdentifier": "",
    "bypassed": false,
    "expanded": true,
    "modPanelOpen": false,
    "gainPanelOpen": false,
    "paramPanelOpen": false,
    "parameters": [
      {
        "paramIndex": 0,
        "name": "Depth",
        "unit": "",
        "minValue": 0.0,
        "maxValue": 1.0,
        "defaultValue": 1.0,
        "currentValue": 0.7,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 1,
        "name": "Time",
        "unit": "",
        "minValue": 0.0,
        "maxValue": 1.0,
        "defaultValue": 0.4,
        "currentValue": 0.32,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 2,
        "name": "Attack",
        "unit": "",
        "minValue": 0.0,
        "maxValue": 1.0,
        "defaultValue": 0.0,
        "currentValue": 0.05,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 3,
        "name": "Input",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 2.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 4,
        "name": "Low Gain",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": -1.5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 5,
        "name": "Mid Gain",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 2.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 6,
        "name": "High Gain",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 2.5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 7,
        "name": "Mix",
        "unit": "",
        "minValue": 0.0,
        "maxValue": 1.0,
        "defaultValue": 1.0,
        "currentValue": 0.8,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 8,
        "name": "Output",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 12.0,
        "defaultValue": 0.0,
        "currentValue": -3.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 9,
        "name": "Low Thresh Above",
        "unit": "dB",
        "minValue": -60.0,
        "maxValue": 0.0,
        "defaultValue": -24.0,
        "currentValue": -20,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 10,
        "name": "Low Thresh Below",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -48.0,
        "currentValue": -46,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 11,
        "name": "Low Ratio Above",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 8.0,
        "currentValue": 4,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 12,
        "name": "Low Ratio Below",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 8.0,
        "currentValue": 5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 13,
        "name": "Low Thresh Expand Below",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -72.0,
        "currentValue": -76,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 14,
        "name": "Low Expand Ratio Below",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 1.0,
        "currentValue": 1.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 15,
        "name": "Low Thresh Expand Above",
        "unit": "dB",
        "minValue": -60.0,
        "maxValue": 0.0,
        "defaultValue": 0.0,
        "currentValue": -5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 16,
        "name": "Low Expand Ratio Above",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 1.0,
        "currentValue": 1.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 17,
        "name": "Low Limit",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 12.0,
        "defaultValue": 0.0,
        "currentValue": -2,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 18,
        "name": "Mid Thresh Above",
        "unit": "dB",
        "minValue": -60.0,
        "maxValue": 0.0,
        "defaultValue": -24.0,
        "currentValue": -28,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 19,
        "name": "Mid Thresh Below",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -48.0,
        "currentValue": -52,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 20,
        "name": "Mid Ratio Above",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 8.0,
        "currentValue": 12,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 21,
        "name": "Mid Ratio Below",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 8.0,
        "currentValue": 15,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 22,
        "name": "Mid Thresh Expand Below",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -72.0,
        "currentValue": -74,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 23,
        "name": "Mid Expand Ratio Below",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 1.0,
        "currentValue": 2.5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 24,
        "name": "Mid Thresh Expand Above",
        "unit": "dB",
        "minValue": -60.0,
        "maxValue": 0.0,
        "defaultValue": 0.0,
        "currentValue": -8,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 25,
        "name": "Mid Expand Ratio Above",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 1.0,
        "currentValue": 3.5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 26,
        "name": "Mid Limit",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 12.0,
        "defaultValue": 0.0,
        "currentValue": -5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 27,
        "name": "High Thresh Above",
        "unit": "dB",
        "minValue": -60.0,
        "maxValue": 0.0,
        "defaultValue": -24.0,
        "currentValue": -32,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 28,
        "name": "High Thresh Below",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -48.0,
        "currentValue": -58,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 29,
        "name": "High Ratio Above",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 8.0,
        "currentValue": 18,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 30,
        "name": "High Ratio Below",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 8.0,
        "currentValue": 18,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 31,
        "name": "High Thresh Expand Below",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -72.0,
        "currentValue": -76,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 32,
        "name": "High Expand Ratio Below",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 1.0,
        "currentValue": 1.5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 33,
        "name": "High Thresh Expand Above",
        "unit": "dB",
        "minValue": -60.0,
        "maxValue": 0.0,
        "defaultValue": 0.0,
        "currentValue": -9,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 34,
        "name": "High Expand Ratio Above",
        "unit": "",
        "minValue": 1.0,
        "maxValue": 50.0,
        "defaultValue": 1.0,
        "currentValue": 4.5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 35,
        "name": "High Limit",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 12.0,
        "defaultValue": 0.0,
        "currentValue": -6,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 36,
        "name": "Low XO",
        "unit": "Hz",
        "minValue": 40.0,
        "maxValue": 500.0,
        "defaultValue": 120.0,
        "currentValue": 160,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 37,
        "name": "High XO",
        "unit": "Hz",
        "minValue": 500.0,
        "maxValue": 8000.0,
        "defaultValue": 2500.0,
        "currentValue": 3000,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      }
    ],
    "visibleParameters": [],
    "gainValue": 1.0,
    "gainDb": 0.0,
    "macros": [],
    "mods": [],
    "currentParameterPage": 0
  }
}
