{
  "magdaVersion": "0.0.0",
  "kind": "device",
  "payload": {
    "id": -1,
    "name": "Multiband Dynamics",
    "pluginId": "magda_multiband",
    "manufacturer": "MAGDA",
    "format": 3,
    "isInstrument": false,
    "deviceType": 1,
    "uniqueId": "",
    "fileOrIdentifier": "",
    "bypassed": false,
    "expanded": true,
    "modPanelOpen": false,
    "gainPanelOpen": false,
    "paramPanelOpen": false,
    "parameters": [
      {
        "paramIndex": 0,
        "name": "Amount",
        "unit": "",
        "minValue": 0.0,
        "maxValue": 1.0,
        "defaultValue": 0.8,
        "currentValue": 1.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 1,
        "name": "Attack",
        "unit": "ms",
        "minValue": 0.1,
        "maxValue": 100.0,
        "defaultValue": 3.0,
        "currentValue": 3.0,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 2,
        "name": "Release",
        "unit": "ms",
        "minValue": 5.0,
        "maxValue": 1000.0,
        "defaultValue": 120.0,
        "currentValue": 120.0,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 3,
        "name": "Input",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 0.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 4,
        "name": "Output",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 0.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 5,
        "name": "Mix",
        "unit": "",
        "minValue": 0.0,
        "maxValue": 1.0,
        "defaultValue": 1.0,
        "currentValue": 1.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 6,
        "name": "Low Input",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 5.2,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 7,
        "name": "Mid Input",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 5.2,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 8,
        "name": "High Input",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 5.2,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 9,
        "name": "Low Output",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 10.3,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 10,
        "name": "Mid Output",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 5.7,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 11,
        "name": "High Output",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 24.0,
        "defaultValue": 0.0,
        "currentValue": 10.3,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 12,
        "name": "Low Lower Threshold",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -48.0,
        "currentValue": -40.8,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 13,
        "name": "Low Upper Threshold",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -24.0,
        "currentValue": -33.8,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 14,
        "name": "Low Below Ratio",
        "unit": "",
        "minValue": 0.05,
        "maxValue": 100.0,
        "defaultValue": 8.0,
        "currentValue": 0.23980815347721823,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 15,
        "name": "Low Above Ratio",
        "unit": "",
        "minValue": 0.05,
        "maxValue": 100.0,
        "defaultValue": 8.0,
        "currentValue": 66.7,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 16,
        "name": "Low Range",
        "unit": "dB",
        "minValue": 0.0,
        "maxValue": 48.0,
        "defaultValue": 24.0,
        "currentValue": 48.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 17,
        "name": "Low Limit",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 12.0,
        "defaultValue": 0.0,
        "currentValue": 0.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 18,
        "name": "Low Attack",
        "unit": "ms",
        "minValue": 0.1,
        "maxValue": 100.0,
        "defaultValue": 3.0,
        "currentValue": 47.8,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 19,
        "name": "Low Release",
        "unit": "ms",
        "minValue": 5.0,
        "maxValue": 1000.0,
        "defaultValue": 120.0,
        "currentValue": 282.0,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 20,
        "name": "Mid Lower Threshold",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -48.0,
        "currentValue": -41.8,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 21,
        "name": "Mid Upper Threshold",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -24.0,
        "currentValue": -30.2,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 22,
        "name": "Mid Below Ratio",
        "unit": "",
        "minValue": 0.05,
        "maxValue": 100.0,
        "defaultValue": 8.0,
        "currentValue": 0.23980815347721823,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 23,
        "name": "Mid Above Ratio",
        "unit": "",
        "minValue": 0.05,
        "maxValue": 100.0,
        "defaultValue": 8.0,
        "currentValue": 66.7,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 24,
        "name": "Mid Range",
        "unit": "dB",
        "minValue": 0.0,
        "maxValue": 48.0,
        "defaultValue": 24.0,
        "currentValue": 48.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 25,
        "name": "Mid Limit",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 12.0,
        "defaultValue": 0.0,
        "currentValue": 0.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 26,
        "name": "Mid Attack",
        "unit": "ms",
        "minValue": 0.1,
        "maxValue": 100.0,
        "defaultValue": 3.0,
        "currentValue": 22.4,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 27,
        "name": "Mid Release",
        "unit": "ms",
        "minValue": 5.0,
        "maxValue": 1000.0,
        "defaultValue": 120.0,
        "currentValue": 282.0,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 28,
        "name": "High Lower Threshold",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -48.0,
        "currentValue": -40.8,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 29,
        "name": "High Upper Threshold",
        "unit": "dB",
        "minValue": -80.0,
        "maxValue": 0.0,
        "defaultValue": -24.0,
        "currentValue": -35.5,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 30,
        "name": "High Below Ratio",
        "unit": "",
        "minValue": 0.05,
        "maxValue": 100.0,
        "defaultValue": 8.0,
        "currentValue": 0.23980815347721823,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 31,
        "name": "High Above Ratio",
        "unit": "",
        "minValue": 0.05,
        "maxValue": 100.0,
        "defaultValue": 8.0,
        "currentValue": 100.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 32,
        "name": "High Range",
        "unit": "dB",
        "minValue": 0.0,
        "maxValue": 48.0,
        "defaultValue": 24.0,
        "currentValue": 48.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 33,
        "name": "High Limit",
        "unit": "dB",
        "minValue": -24.0,
        "maxValue": 12.0,
        "defaultValue": 0.0,
        "currentValue": 0.0,
        "scale": 0,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 34,
        "name": "High Attack",
        "unit": "ms",
        "minValue": 0.1,
        "maxValue": 100.0,
        "defaultValue": 3.0,
        "currentValue": 13.5,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 35,
        "name": "High Release",
        "unit": "ms",
        "minValue": 5.0,
        "maxValue": 1000.0,
        "defaultValue": 120.0,
        "currentValue": 132.0,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 36,
        "name": "Low XO",
        "unit": "Hz",
        "minValue": 40.0,
        "maxValue": 500.0,
        "defaultValue": 120.0,
        "currentValue": 88.3,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      },
      {
        "paramIndex": 37,
        "name": "High XO",
        "unit": "Hz",
        "minValue": 500.0,
        "maxValue": 8000.0,
        "defaultValue": 2500.0,
        "currentValue": 2500.0,
        "scale": 1,
        "skewFactor": 1.0,
        "modulatable": true,
        "bipolarModulation": false,
        "choices": []
      }
    ],
    "visibleParameters": [],
    "gainValue": 1.0,
    "gainDb": 0.0,
    "macros": [],
    "mods": [],
    "currentParameterPage": 0
  }
}
